print("Введите любые четыре числа:")
a = float(input("a = "))
b = float(input("b = "))
c = float(input("c = "))
d = float(input("d = "))
i = (a + b)/(c + d)
print("Результат вычислений:", "%.2f" % i)
